### ISSUE TITLE
Needless use of sudo

### ISSUE THREAD

**Issue by ver4a** [stemid/hyprland-fedora-image#1]
You're using sudo _a lot_, there are many reasons not to do this, among them:

1. The default user:group is already 0:0
2. sudo throws away environment before running, therefore commands run without sudo will behave differently from those run with it, making the build a nightmare to debug :)

**Comment by stemid** [comment]
Thanks, I'll take care of that.

I knew the default uid was 0 but I had been copy&pasting the same line into a toolbox container for local testing, hence all the sudo calls.

**Comment by ver4a** [comment]
I see, I recommend testing on the same base image you're working on, that will also allow you to uncover problems before you try to integrate.
